#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPrime.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Prime")]
	public partial class PrimeDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertbook_info_table(book_info_table instance);
    partial void Updatebook_info_table(book_info_table instance);
    partial void Deletebook_info_table(book_info_table instance);
    partial void Insertcharge_info_table(charge_info_table instance);
    partial void Updatecharge_info_table(charge_info_table instance);
    partial void Deletecharge_info_table(charge_info_table instance);
    partial void Insertmedical_devices_info_table(medical_devices_info_table instance);
    partial void Updatemedical_devices_info_table(medical_devices_info_table instance);
    partial void Deletemedical_devices_info_table(medical_devices_info_table instance);
    partial void Insertuser_info_table(user_info_table instance);
    partial void Updateuser_info_table(user_info_table instance);
    partial void Deleteuser_info_table(user_info_table instance);
    partial void Inserttreat_table(treat_table instance);
    partial void Updatetreat_table(treat_table instance);
    partial void Deletetreat_table(treat_table instance);
    partial void Insertcase_info(case_info instance);
    partial void Updatecase_info(case_info instance);
    partial void Deletecase_info(case_info instance);
    #endregion
		
		public PrimeDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PrimeConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PrimeDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PrimeDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PrimeDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PrimeDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<book_info_table> book_info_table
		{
			get
			{
				return this.GetTable<book_info_table>();
			}
		}
		
		public System.Data.Linq.Table<charge_info_table> charge_info_table
		{
			get
			{
				return this.GetTable<charge_info_table>();
			}
		}
		
		public System.Data.Linq.Table<medical_devices_info_table> medical_devices_info_table
		{
			get
			{
				return this.GetTable<medical_devices_info_table>();
			}
		}
		
		public System.Data.Linq.Table<user_info_table> user_info_table
		{
			get
			{
				return this.GetTable<user_info_table>();
			}
		}
		
		public System.Data.Linq.Table<treat_table> treat_table
		{
			get
			{
				return this.GetTable<treat_table>();
			}
		}
		
		public System.Data.Linq.Table<case_info> case_info
		{
			get
			{
				return this.GetTable<case_info>();
			}
		}
		
		public System.Data.Linq.Table<case_to_treat> case_to_treat
		{
			get
			{
				return this.GetTable<case_to_treat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.book_info_table")]
	public partial class book_info_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _book_num;
		
		private long _patient_id;
		
		private long _dentist_id;
		
		private System.DateTime _book_gen_time;
		
		private System.DateTime _book_time;
		
		private int _book_state;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbook_numChanging(long value);
    partial void Onbook_numChanged();
    partial void Onpatient_idChanging(long value);
    partial void Onpatient_idChanged();
    partial void Ondentist_idChanging(long value);
    partial void Ondentist_idChanged();
    partial void Onbook_gen_timeChanging(System.DateTime value);
    partial void Onbook_gen_timeChanged();
    partial void Onbook_timeChanging(System.DateTime value);
    partial void Onbook_timeChanged();
    partial void Onbook_stateChanging(int value);
    partial void Onbook_stateChanged();
    #endregion
		
		public book_info_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_num", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long book_num
		{
			get
			{
				return this._book_num;
			}
			set
			{
				if ((this._book_num != value))
				{
					this.Onbook_numChanging(value);
					this.SendPropertyChanging();
					this._book_num = value;
					this.SendPropertyChanged("book_num");
					this.Onbook_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_id", DbType="BigInt NOT NULL")]
		public long patient_id
		{
			get
			{
				return this._patient_id;
			}
			set
			{
				if ((this._patient_id != value))
				{
					this.Onpatient_idChanging(value);
					this.SendPropertyChanging();
					this._patient_id = value;
					this.SendPropertyChanged("patient_id");
					this.Onpatient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dentist_id", DbType="BigInt NOT NULL")]
		public long dentist_id
		{
			get
			{
				return this._dentist_id;
			}
			set
			{
				if ((this._dentist_id != value))
				{
					this.Ondentist_idChanging(value);
					this.SendPropertyChanging();
					this._dentist_id = value;
					this.SendPropertyChanged("dentist_id");
					this.Ondentist_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_gen_time", DbType="DateTime NOT NULL")]
		public System.DateTime book_gen_time
		{
			get
			{
				return this._book_gen_time;
			}
			set
			{
				if ((this._book_gen_time != value))
				{
					this.Onbook_gen_timeChanging(value);
					this.SendPropertyChanging();
					this._book_gen_time = value;
					this.SendPropertyChanged("book_gen_time");
					this.Onbook_gen_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_time", DbType="DateTime NOT NULL")]
		public System.DateTime book_time
		{
			get
			{
				return this._book_time;
			}
			set
			{
				if ((this._book_time != value))
				{
					this.Onbook_timeChanging(value);
					this.SendPropertyChanging();
					this._book_time = value;
					this.SendPropertyChanged("book_time");
					this.Onbook_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_state", DbType="Int NOT NULL")]
		public int book_state
		{
			get
			{
				return this._book_state;
			}
			set
			{
				if ((this._book_state != value))
				{
					this.Onbook_stateChanging(value);
					this.SendPropertyChanging();
					this._book_state = value;
					this.SendPropertyChanged("book_state");
					this.Onbook_stateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.charge_info_table")]
	public partial class charge_info_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _charge_id;
		
		private long _patient_id;
		
		private System.Nullable<decimal> _balance;
		
		private System.Nullable<long> _treat_id;
		
		private System.Nullable<System.DateTime> _charge_gen_time;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncharge_idChanging(long value);
    partial void Oncharge_idChanged();
    partial void Onpatient_idChanging(long value);
    partial void Onpatient_idChanged();
    partial void OnbalanceChanging(System.Nullable<decimal> value);
    partial void OnbalanceChanged();
    partial void Ontreat_idChanging(System.Nullable<long> value);
    partial void Ontreat_idChanged();
    partial void Oncharge_gen_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncharge_gen_timeChanged();
    #endregion
		
		public charge_info_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_charge_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long charge_id
		{
			get
			{
				return this._charge_id;
			}
			set
			{
				if ((this._charge_id != value))
				{
					this.Oncharge_idChanging(value);
					this.SendPropertyChanging();
					this._charge_id = value;
					this.SendPropertyChanged("charge_id");
					this.Oncharge_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long patient_id
		{
			get
			{
				return this._patient_id;
			}
			set
			{
				if ((this._patient_id != value))
				{
					this.Onpatient_idChanging(value);
					this.SendPropertyChanging();
					this._patient_id = value;
					this.SendPropertyChanged("patient_id");
					this.Onpatient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="Money")]
		public System.Nullable<decimal> balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treat_id", DbType="BigInt")]
		public System.Nullable<long> treat_id
		{
			get
			{
				return this._treat_id;
			}
			set
			{
				if ((this._treat_id != value))
				{
					this.Ontreat_idChanging(value);
					this.SendPropertyChanging();
					this._treat_id = value;
					this.SendPropertyChanged("treat_id");
					this.Ontreat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_charge_gen_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> charge_gen_time
		{
			get
			{
				return this._charge_gen_time;
			}
			set
			{
				if ((this._charge_gen_time != value))
				{
					this.Oncharge_gen_timeChanging(value);
					this.SendPropertyChanging();
					this._charge_gen_time = value;
					this.SendPropertyChanged("charge_gen_time");
					this.Oncharge_gen_timeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medical_devices_info_table")]
	public partial class medical_devices_info_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _medical_devices_id;
		
		private string _medical_devices_type;
		
		private string _medical_devices_name;
		
		private long _amount;
		
		private decimal _unitprice;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmedical_devices_idChanging(long value);
    partial void Onmedical_devices_idChanged();
    partial void Onmedical_devices_typeChanging(string value);
    partial void Onmedical_devices_typeChanged();
    partial void Onmedical_devices_nameChanging(string value);
    partial void Onmedical_devices_nameChanged();
    partial void OnamountChanging(long value);
    partial void OnamountChanged();
    partial void OnunitpriceChanging(decimal value);
    partial void OnunitpriceChanged();
    #endregion
		
		public medical_devices_info_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medical_devices_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long medical_devices_id
		{
			get
			{
				return this._medical_devices_id;
			}
			set
			{
				if ((this._medical_devices_id != value))
				{
					this.Onmedical_devices_idChanging(value);
					this.SendPropertyChanging();
					this._medical_devices_id = value;
					this.SendPropertyChanged("medical_devices_id");
					this.Onmedical_devices_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medical_devices_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string medical_devices_type
		{
			get
			{
				return this._medical_devices_type;
			}
			set
			{
				if ((this._medical_devices_type != value))
				{
					this.Onmedical_devices_typeChanging(value);
					this.SendPropertyChanging();
					this._medical_devices_type = value;
					this.SendPropertyChanged("medical_devices_type");
					this.Onmedical_devices_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medical_devices_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string medical_devices_name
		{
			get
			{
				return this._medical_devices_name;
			}
			set
			{
				if ((this._medical_devices_name != value))
				{
					this.Onmedical_devices_nameChanging(value);
					this.SendPropertyChanging();
					this._medical_devices_name = value;
					this.SendPropertyChanged("medical_devices_name");
					this.Onmedical_devices_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="BigInt NOT NULL")]
		public long amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitprice", DbType="Money NOT NULL")]
		public decimal unitprice
		{
			get
			{
				return this._unitprice;
			}
			set
			{
				if ((this._unitprice != value))
				{
					this.OnunitpriceChanging(value);
					this.SendPropertyChanging();
					this._unitprice = value;
					this.SendPropertyChanged("unitprice");
					this.OnunitpriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_info_table")]
	public partial class user_info_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _user_id;
		
		private string _account_name;
		
		private string _pwd;
		
		private int _user_type;
		
		private System.Nullable<int> _user_gender;
		
		private string _user_name;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _id_num;
		
		private string _tel;
		
		private string _user_describe;
		
		private string _user_photo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void Onaccount_nameChanging(string value);
    partial void Onaccount_nameChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void Onuser_typeChanging(int value);
    partial void Onuser_typeChanged();
    partial void Onuser_genderChanging(System.Nullable<int> value);
    partial void Onuser_genderChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void Onid_numChanging(string value);
    partial void Onid_numChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void Onuser_describeChanging(string value);
    partial void Onuser_describeChanged();
    partial void Onuser_photoChanging(string value);
    partial void Onuser_photoChanged();
    #endregion
		
		public user_info_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string account_name
		{
			get
			{
				return this._account_name;
			}
			set
			{
				if ((this._account_name != value))
				{
					this.Onaccount_nameChanging(value);
					this.SendPropertyChanging();
					this._account_name = value;
					this.SendPropertyChanged("account_name");
					this.Onaccount_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				if ((this._pwd != value))
				{
					this.OnpwdChanging(value);
					this.SendPropertyChanging();
					this._pwd = value;
					this.SendPropertyChanged("pwd");
					this.OnpwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="Int NOT NULL")]
		public int user_type
		{
			get
			{
				return this._user_type;
			}
			set
			{
				if ((this._user_type != value))
				{
					this.Onuser_typeChanging(value);
					this.SendPropertyChanging();
					this._user_type = value;
					this.SendPropertyChanged("user_type");
					this.Onuser_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_gender", DbType="Int")]
		public System.Nullable<int> user_gender
		{
			get
			{
				return this._user_gender;
			}
			set
			{
				if ((this._user_gender != value))
				{
					this.Onuser_genderChanging(value);
					this.SendPropertyChanging();
					this._user_gender = value;
					this.SendPropertyChanged("user_gender");
					this.Onuser_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_num", DbType="VarChar(50)")]
		public string id_num
		{
			get
			{
				return this._id_num;
			}
			set
			{
				if ((this._id_num != value))
				{
					this.Onid_numChanging(value);
					this.SendPropertyChanging();
					this._id_num = value;
					this.SendPropertyChanged("id_num");
					this.Onid_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(50)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_describe", DbType="NVarChar(MAX)")]
		public string user_describe
		{
			get
			{
				return this._user_describe;
			}
			set
			{
				if ((this._user_describe != value))
				{
					this.Onuser_describeChanging(value);
					this.SendPropertyChanging();
					this._user_describe = value;
					this.SendPropertyChanged("user_describe");
					this.Onuser_describeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_photo", DbType="NVarChar(50)")]
		public string user_photo
		{
			get
			{
				return this._user_photo;
			}
			set
			{
				if ((this._user_photo != value))
				{
					this.Onuser_photoChanging(value);
					this.SendPropertyChanging();
					this._user_photo = value;
					this.SendPropertyChanged("user_photo");
					this.Onuser_photoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.treat_table")]
	public partial class treat_table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _treat_id;
		
		private decimal _charge;
		
		private string _treat_name;
		
		private string _treat_note;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontreat_idChanging(long value);
    partial void Ontreat_idChanged();
    partial void OnchargeChanging(decimal value);
    partial void OnchargeChanged();
    partial void Ontreat_nameChanging(string value);
    partial void Ontreat_nameChanged();
    partial void Ontreat_noteChanging(string value);
    partial void Ontreat_noteChanged();
    #endregion
		
		public treat_table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treat_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long treat_id
		{
			get
			{
				return this._treat_id;
			}
			set
			{
				if ((this._treat_id != value))
				{
					this.Ontreat_idChanging(value);
					this.SendPropertyChanging();
					this._treat_id = value;
					this.SendPropertyChanged("treat_id");
					this.Ontreat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_charge", DbType="Money NOT NULL")]
		public decimal charge
		{
			get
			{
				return this._charge;
			}
			set
			{
				if ((this._charge != value))
				{
					this.OnchargeChanging(value);
					this.SendPropertyChanging();
					this._charge = value;
					this.SendPropertyChanged("charge");
					this.OnchargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treat_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string treat_name
		{
			get
			{
				return this._treat_name;
			}
			set
			{
				if ((this._treat_name != value))
				{
					this.Ontreat_nameChanging(value);
					this.SendPropertyChanging();
					this._treat_name = value;
					this.SendPropertyChanged("treat_name");
					this.Ontreat_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treat_note", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string treat_note
		{
			get
			{
				return this._treat_note;
			}
			set
			{
				if ((this._treat_note != value))
				{
					this.Ontreat_noteChanging(value);
					this.SendPropertyChanging();
					this._treat_note = value;
					this.SendPropertyChanged("treat_note");
					this.Ontreat_noteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.case_info")]
	public partial class case_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _case_id;
		
		private long _patient_id;
		
		private long _dentist_id;
		
		private System.DateTime _case_gen_time;
		
		private string _case_note;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncase_idChanging(long value);
    partial void Oncase_idChanged();
    partial void Onpatient_idChanging(long value);
    partial void Onpatient_idChanged();
    partial void Ondentist_idChanging(long value);
    partial void Ondentist_idChanged();
    partial void Oncase_gen_timeChanging(System.DateTime value);
    partial void Oncase_gen_timeChanged();
    partial void Oncase_noteChanging(string value);
    partial void Oncase_noteChanged();
    #endregion
		
		public case_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this.Oncase_idChanging(value);
					this.SendPropertyChanging();
					this._case_id = value;
					this.SendPropertyChanged("case_id");
					this.Oncase_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_id", DbType="BigInt NOT NULL")]
		public long patient_id
		{
			get
			{
				return this._patient_id;
			}
			set
			{
				if ((this._patient_id != value))
				{
					this.Onpatient_idChanging(value);
					this.SendPropertyChanging();
					this._patient_id = value;
					this.SendPropertyChanged("patient_id");
					this.Onpatient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dentist_id", DbType="BigInt NOT NULL")]
		public long dentist_id
		{
			get
			{
				return this._dentist_id;
			}
			set
			{
				if ((this._dentist_id != value))
				{
					this.Ondentist_idChanging(value);
					this.SendPropertyChanging();
					this._dentist_id = value;
					this.SendPropertyChanged("dentist_id");
					this.Ondentist_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_gen_time", DbType="DateTime NOT NULL")]
		public System.DateTime case_gen_time
		{
			get
			{
				return this._case_gen_time;
			}
			set
			{
				if ((this._case_gen_time != value))
				{
					this.Oncase_gen_timeChanging(value);
					this.SendPropertyChanging();
					this._case_gen_time = value;
					this.SendPropertyChanged("case_gen_time");
					this.Oncase_gen_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_note", DbType="NVarChar(50)")]
		public string case_note
		{
			get
			{
				return this._case_note;
			}
			set
			{
				if ((this._case_note != value))
				{
					this.Oncase_noteChanging(value);
					this.SendPropertyChanging();
					this._case_note = value;
					this.SendPropertyChanged("case_note");
					this.Oncase_noteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.case_to_treat")]
	public partial class case_to_treat
	{
		
		private long _case_treat_id;
		
		private long _case_id;
		
		private long _treat_id;
		
		private int _treat_count;
		
		public case_to_treat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_treat_id", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long case_treat_id
		{
			get
			{
				return this._case_treat_id;
			}
			set
			{
				if ((this._case_treat_id != value))
				{
					this._case_treat_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_case_id", DbType="BigInt NOT NULL")]
		public long case_id
		{
			get
			{
				return this._case_id;
			}
			set
			{
				if ((this._case_id != value))
				{
					this._case_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treat_id", DbType="BigInt NOT NULL")]
		public long treat_id
		{
			get
			{
				return this._treat_id;
			}
			set
			{
				if ((this._treat_id != value))
				{
					this._treat_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_treat_count", DbType="Int NOT NULL")]
		public int treat_count
		{
			get
			{
				return this._treat_count;
			}
			set
			{
				if ((this._treat_count != value))
				{
					this._treat_count = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
